# Generated by Django 5.2.3 on 2025-06-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('phones', 'Phones'), ('laptops', 'Laptops'), ('tablets', 'Tablets'), ('headphones', 'Headphones'), ('speakers', 'Speakers'), ('cameras', 'Cameras'), ('gaming', 'Gaming'), ('smartwatches', 'Smartwatches'), ('smarthome', 'Smart Home'), ('other', 'Other')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
